parameters:
    #foo: bar

services:
    blade_tester_light_news.forms.news:
        class: "%blade_tester_light_news.form.type.news.class%"
        arguments: ["%blade_tester_light_news.form.type.news.entity%"]

    blade_tester_light_news.entity.news:
        class: "%blade_tester_light_news.form.type.news.entity%"

    blade_tester_light_news.news_manager:
        class: "BladeTester\\LightNewsBundle\\Doctrine\\NewsManager"
        arguments: ["@doctrine.orm.entity_manager", '%blade_tester_light_news.form.type.news.entity%']